title        = "SPIFFE"
baseURL      = "/"
languageCode = "en-us"
pygmentsStyle = "monokai"
pygmentsCodefences = true
canonifyurls = true
googleAnalytics = "UA-99605331-1"
enableGitInfo = true
publicUrl = "https://spiffe.io"
spireGitHubUrl = "https://github.com/spiffe/spire"

[markup]
  [markup.tableOfContents]
    startLevel = 1

[params]
acronym = "Secure Production Identity Framework for Everyone"
assetintegritychecking = false
githuburl = "https://github.com/spiffe/spiffe.io/tree/master"

[params.home]
acronym     = "**S**ecure **P**roduction **I**dentity **F**ramework **f**or **E**veryone"
description = "A universal identity control plane for distributed systems"

[params.home.whatis]
spiffe = "**SPIFFE**, the Secure Production Identity Framework For Everyone, provides a secure identity, in the form of a specially crafted X.509 certificate, to every workload in a modern production environment. SPIFFE removes the need for application-level authentication and complex network-level ACL configuration. "
spire = "**SPIRE**, the SPIFFE Runtime Environment, is an extensible system that implements the principles embodied in the SPIFFE standards. SPIRE manages platform and workload attestation, provides an API for controlling attestation policies, and coordinates certificate issuance and rotation."

[params.socialmedia]
twitter       = "SPIFFEio"
slack         = "https://slack.spiffe.io/"
medium        = "https://blog.spiffe.io/"
github        = "https://github.com/spiffe"
stackoverflow = "https://stackoverflow.com/questions/tagged/spiffe"
youtube       = "https://www.youtube.com/channel/UCVzeW7j02FDNggkI5JKPvJg/f"

[params.assets]
js = [
    "jquery-3.3.1",
    "clipboard-2.0.0",
    "anchor-4.1.1",
    "app",
    "slider"
]

[params.docs.assets]
js = [
    "docs"
]

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^BRANCH$', '^HIDE_RELEASES$']
